apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-event
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/oleksandralukianova/Desktop/k8s/19_microservices/db/data"

